export const TAROT_CARDS = [
  { id: 0, name: 'The Fool', zhName: '愚者', image: '/tarot/m00.jpg' },
  { id: 1, name: 'The Magician', zhName: '魔术师', image: '/tarot/m01.jpg' },
  { id: 2, name: 'The High Priestess', zhName: '女祭司', image: '/tarot/m02.jpg' },
  { id: 3, name: 'The Empress', zhName: '皇后', image: '/tarot/m03.jpg' },
  { id: 4, name: 'The Emperor', zhName: '皇帝', image: '/tarot/m04.jpg' },
  { id: 5, name: 'The Hierophant', zhName: '教皇', image: '/tarot/m05.jpg' },
  { id: 6, name: 'The Lovers', zhName: '恋人', image: '/tarot/m06.jpg' },
  { id: 7, name: 'The Chariot', zhName: '战车', image: '/tarot/m07.jpg' },
  { id: 8, name: 'Strength', zhName: '力量', image: '/tarot/m08.jpg' },
  { id: 9, name: 'The Hermit', zhName: '隐士', image: '/tarot/m09.jpg' },
  { id: 10, name: 'Wheel of Fortune', zhName: '命运之轮', image: '/tarot/m10.jpg' },
  { id: 11, name: 'Justice', zhName: '正义', image: '/tarot/m11.jpg' },
  { id: 12, name: 'The Hanged Man', zhName: '倒吊人', image: '/tarot/m12.jpg' },
  { id: 13, name: 'Death', zhName: '死神', image: '/tarot/m13.jpg' },
  { id: 14, name: 'Temperance', zhName: '节制', image: '/tarot/m14.jpg' },
  { id: 15, name: 'The Devil', zhName: '恶魔', image: '/tarot/m15.jpg' },
  { id: 16, name: 'The Tower', zhName: '高塔', image: '/tarot/m16.jpg' },
  { id: 17, name: 'The Star', zhName: '星星', image: '/tarot/m17.jpg' },
  { id: 18, name: 'The Moon', zhName: '月亮', image: '/tarot/m18.jpg' },
  { id: 19, name: 'The Sun', zhName: '太阳', image: '/tarot/m19.jpg' },
  { id: 20, name: 'Judgement', zhName: '审判', image: '/tarot/m20.jpg' },
  { id: 21, name: 'The World', zhName: '世界', image: '/tarot/m21.jpg' },
];

export type ModuleType = 'home' | 'tarot' | 'astrology' | 'bazi';
